[project]
name = "brain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "google-genai>=1.47.0",
    "httpx>=0.28.1",
    "openai>=2.16.0",
    "python-dotenv>=1.2.1",
]
